services:
  rclone:
    image: rclone/rclone:1.74.4
    container_name: proton-rclone
    restart: unless-stopped
    tty: true
    stdin_open: true
    entrypoint: /bin/sh
    command: -c "sleep infinity"

    volumes:
      # Stores the rclone configuration
      - ./config:/config/rclone

      # Change the path on the LEFT to your own NAS folder.
      # Example:
      # "/volume1/Family Photos:/data/photo:ro"
      #
      # :ro = read-only. rclone can read the files,
      # but cannot modify or delete the originals.
      - "/path/to/your/photos:/data/photo:ro"
