services:
  rclone:
    image: rclone/rclone:1.74.4
    container_name: proton-rclone
    restart: unless-stopped
    tty: true
    stdin_open: true
    entrypoint: /bin/sh
    command: -c "sleep infinity"

    volumes:
      # Stores the rclone configuration
      - ./config:/config/rclone

      # Choose the NAS folder you want to back up.
      #
      # Change ONLY the path on the LEFT to your own NAS folder.
      #
      # Example:
      # - "/volume1/Documents:/data/backup:ro"
      #
      # /data/backup is the folder name used inside the container.
      # :ro = read-only. rclone can read your files,
      # but cannot modify or delete the originals on the NAS.
      - "/path/to/your/folder:/data/backup:ro"

